# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.1.48"

  on_macos do
    on_intel do
      sha256 "a0c2c284a753148821edac490caeb5d80a4f8f6dbbc79662b85fac88e088c34b"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6f542244c738a573c35c24354c0a4730c1ef289fcea20c023c55bd2d0ab18ede"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "189b4d7dfea858e1b3ccb0eb499b255d6419c8d4f42866ca2528e0979b4ca8fd"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "59087190710724929ecc85c895fa744e71b24d191a8ab2b34c01577f60716aaa"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Rubber Duck CLI — pull course lessons, run challenge tests locally, submit solutions"
  homepage "https://github.com/michael-duren/rubber-duck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
