# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.1.46"

  on_macos do
    on_intel do
      sha256 "3599f7d87f17d7775f612b34f35a88f1d231596c0ce8fcc141b16959f427dc55"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c6f1f18bbaf65c1d3b52ae1776a66430bc49bd1da5d23c732f57dd9b80b1b42b"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d68fcf351e3f6db8c42dedc737ce54d15261189d3389e338ccb617c3b01a981"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ac911be7a4da4d6e75e5f6d141825e0e94322091befc31dd3775c5dcdeb5bf33"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Rubber Duck CLI — pull course lessons, run challenge tests locally, submit solutions"
  homepage "https://github.com/michael-duren/rubber-duck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
