# This file was generated by GoReleaser. DO NOT EDIT.
cask "duck" do
  version "0.1.42"

  on_macos do
    on_intel do
      sha256 "f747a8bda90fb9d04d101f401454260f3843da740e58f44db220f9be205d6003"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7c1028586bb5e2afd31dcb83e76f09976c201aa34693b73fcaef597fb4b3ca99"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1056cacb9b928594afbc2e7ec5ef399fbd62edd06de5f9af14cc9166e01c7a58"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "372d9f70965202c1ff0921919e85fe01de0de2b129b18925b0410b3d74b8e742"
      url "https://github.com/michael-duren/rubber-duck/releases/download/v#{version}/duck_Linux_arm64.tar.gz"
    end
  end

  name "duck"
  desc "Rubber Duck CLI — pull course lessons, run challenge tests locally, submit solutions"
  homepage "https://github.com/michael-duren/rubber-duck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duck"]
    end
  end

  # No zap stanza required

end
